version: "3.7"
   
services:
  db:
    image: postgres:11
    container_name: postgres_dev
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - 5432:5432
    volumes:
      - ./db:/var/lib/postgresql/data
